# Generated by Django 3.2.7 on 2022-10-22 13:15

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valid_to', models.DateTimeField()),
                ('cvc_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('card_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=6)),
                ('currency', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'db_table': 'card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('registration_address', models.CharField(max_length=300)),
                ('residential_address', models.CharField(max_length=300)),
                ('client_type', models.CharField(max_length=20)),
                ('ogrn', models.CharField(max_length=20, unique=True)),
                ('inn', models.CharField(max_length=20, unique=True)),
                ('kpp', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('loan_agreement', 'Loan Agreement'), ('bank_account_agreement', 'Bank Account Agreement'), ('settlement_and_cash_service_agreement', 'Settlement And Cash Service Agreement')], default='settlement_and_cash_service_agreement', max_length=37)),
                ('conclusion_date', models.DateField(default=django.utils.timezone.now)),
                ('contract_content', models.TextField()),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'contract',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=2)),
                ('conclusion_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
                'db_table': 'credit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=2)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=2)),
                ('repayment_of_interest_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sum_repayment_loan_part', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
            ],
            options={
                'verbose_name': 'Payment Schedule',
                'verbose_name_plural': 'Payment Schedules',
                'db_table': 'payment_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
    ]
