# Generated by Django 3.2.7 on 2022-10-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=10)),
                ('summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_datetime', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
                'managed': False,
            },
        ),
    ]
