/*
 * Swagger banking api simulation - OpenAPI 3.0
 *
 * Banking simulation application
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	"github.com/dopefresh/banking/golang/banking/src"
)

func main() {
	log.Printf("Server started")

	router := src.NewRouter()

	log.Fatal(router.Run(":8080"))
}
