/*
 * Swagger banking api simulation - OpenAPI 3.0
 *
 * Banking simulation application
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package handlers

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetPaymentSchedule - get payment schedule by id
func GetPaymentSchedule(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetPaymentSchedules - Get client's credit payment schedules
func GetPaymentSchedules(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
