/*
 * Swagger banking api simulation - OpenAPI 3.0
 *
 * Banking simulation application
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import "github.com/shopspring/decimal"

type Transfer struct {
	CardFromId string `json:"cardFromId,omitempty"`

	CardToId string `json:"cardToId,omitempty"`

	Summ decimal.Decimal `json:"summ,omitempty"`
}
