/*
 * Swagger banking api simulation - OpenAPI 3.0
 *
 * Banking simulation application
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CardCreate struct {
	CardId string `json:"cardId,omitempty" gorm:"primaryKey"`

	Balance float64 `json:"balance,omitempty" sql:"type:numeric(12,2)"`

	ValidTo string `json:"validTo,omitempty"`

	CvcCode string `json:"cvcCode,omitempty"`

	CardType string `json:"cardType,omitempty" gorm:"type:card_type"`

	Currency string `json:"currency,omitempty"`

	ClientId int64 `json:"clientId,omitempty"`
}

func (CardCreate) TableName() string {
	return "card"
}
