/*
 * Swagger banking api simulation - OpenAPI 3.0
 *
 * Banking simulation application
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type PaymentSchedule struct {
	PaymentScheduleId int64 `json:"paymentScheduleId,omitempty"`

	TotalSum float64 `json:"totalSum,omitempty"`

	Currency string `json:"currency,omitempty"`

	Commision float64 `json:"commision,omitempty"`

	RepaymentOfInterestSum float64 `json:"repaymentOfInterestSum,omitempty"`

	SumRepaymentLoanPart float64 `json:"sumRepaymentLoanPart,omitempty"`

	DateBegin string `json:"dateBegin,omitempty"`

	DateEnd string `json:"dateEnd,omitempty"`

	ContractId int64 `json:"contractId,omitempty"`
}
