/*
 * Swagger banking api simulation - OpenAPI 3.0
 *
 * Banking simulation application
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"

	"github.com/shopspring/decimal"
)

type Transaction struct {
	TransactionId int64 `json:"transactionId,omitempty" gorm:"primaryKey"`

	TransactionType TransactionType `json:"transactionType,omitempty" gorm:"type:transaction_type"`

	CardFromId string `json:"cardIdFrom,omitempty" gorm:"default:null"`

	CardToId string `json:"cardIdTo,omitempty" gorm:"default:null"`
	CardId   string `json:"cardId,omitempty" gorm:"default:null"`

	Summ decimal.Decimal `json:"summ,omitempty" sql:"type:numeric(12,2)"`

	TransactionDatetime time.Time `json:"transactionDatetime,omitempty" gorm:"default:null"`
}

func (Transaction) TableName() string {
	return "transaction"
}
