/*
 * Swagger banking api simulation - OpenAPI 3.0
 *
 * Banking simulation application
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"time"

	"github.com/shopspring/decimal"
)

type Card struct {
	CardId string `json:"cardId,omitempty" gorm:"primaryKey"`

	Balance decimal.Decimal `json:"balance,omitempty" sql:"type:numeric(12,2)"`

	ValidTo time.Time `json:"validTo,omitempty"`

	CvcCode string `json:"cvcCode,omitempty"`

	CardType CardType `json:"cardType,omitempty" gorm:"type:card_type"`

	Currency string `json:"currency,omitempty"`

	ClientId int64 `json:"clientId,omitempty"`

	Client Client `gorm:"foreignKey:ClientId"`
}

func (Card) TableName() string {
	return "card"
}
