/*
 * Swagger banking api simulation - OpenAPI 3.0
 *
 * Banking simulation application
 *
 * API version: 1.0.11
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type CreditCreate struct {

	Summ float64 `json:"summ,omitempty"`

	Percent float64 `json:"percent,omitempty"`

	ConclusionDate string `json:"conclusionDate,omitempty"`

	EndDate string `json:"endDate,omitempty"`

	ContractId int64 `json:"contractId,omitempty"`
}
